version: '3.9'

services:
  rest_db:
      container_name: rest-pg-db
      restart: unless-stopped
      build:
        context: .
        dockerfile: dockerfile/Dockerfile.postgres
      ports:
        - "5433:5432"
      env_file:
        - docker.env
      volumes:
        - rest-pg-data:/var/lib/postgresql/data
      networks:
        - rest-network

  rest_server:
    container_name: rest-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.nodejs.dev
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    command: yarn start
    depends_on:
      - rest_db
    networks:
      - rest-network

  rest_redis:
    container_name: rest-redis-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.redis-server
    ports:
      - "6379:6379"
    networks:
      - rest-network

volumes:
  rest-pg-data:

networks:
  rest-network: