version: '3.9'

services:
  payment_db:
      container_name: payment-pg-db
      restart: unless-stopped
      build:
        context: .
        dockerfile: dockerfile/Dockerfile.postgres
      ports:
        - "5434:5432"
      env_file:
        - docker.env
      volumes:
        - payment-pg-data:/var/lib/postgresql/data
      networks:
        - payment-network

  payment_server:
    container_name: payment-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.nodejs.dev
    volumes:
      - ./src:/app
    ports:
      - "8082:3000"
    # command: yarn start
    depends_on:
      - payment_db
    networks:
      - payment-network

volumes:
  payment-pg-data:

networks:
  payment-network: